on:
  # Triggers the workflow on push to main
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build project
        run: |
          npm install
          npm run build
          
      - name: Deploy build
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: build
